Change Updatenotification
nextcloud/vm pull request #2461
Opened 2023-03-31 11:30 UTC by enoch85

2023-03-31 16:22 UTC, enoch85 commented
> Hm... Is there a specific reason why the update script should only run once a month and not every week? This means some instances might be vulnerable in worst case for a whole month without any updates installed...

Yes, it's about uptime. I'm aware of the downside, but if you want to update more frequently then you can just change the crontab. Once per month is enough from a security standpoint if you ask me. In worst case, some CVE might not be patched instantly (aka next week) but 3 weeks more is not a problem I'd say - maybe if you're a government, but not a "regular user".

2023-04-01 21:32 UTC, szaimen requested changes

2023-04-01 21:32 UTC, szaimen commented on nextcloud_install_production.sh
> +crontab -u root -l | { cat; echo "59 $AUT_UPDATES_TIME * 1-12 6 $SCRIPTS/updatenotification.sh > /dev/null 2>&1"; } | crontab -u root -
I would adjust this. The logic is there to only send the notification once even though the acript runs daily.

2023-04-01 21:32 UTC, szaimen commented on nextcloud_update.sh
> +    crontab -u root -l | grep -v "$SCRIPTS/updatenotification.sh" | crontab -u root -
I wouldn adjust this

2023-04-01 21:32 UTC, szaimen commented on nextcloud_update.sh
> +    crontab -u root -l | { cat; echo "59 $AUT_UPDATES_TIME * * 5 $SCRIPTS/updatenotification.sh > /dev/null 2>&1"; } | crontab -u root -
Same

2023-04-01 21:32 UTC, szaimen commented on static/updatenotification.sh
> +Updates every month on Saturdays at $AUT_UPDATES_TIME:00, you don't need to bother about updating \
Looks good

2023-04-01 21:35 UTC, szaimen reviewed
So if you really want to change it to monthly adjusting only the wording shoupd be enough

2023-04-01 23:52 UTC, merged